### ISSUE TITLE
Unable to type in search field after going back to previous page

### ISSUE THREAD

**Issue by orangeblock** [zk/clojuredocs#182]
I've tried on Firefox and Chrome. This is only an issue on Firefox. 

To reproduce:
- Go to main page or any other document page and start typing in the search box.
- Click on one of the autocomplete suggestions.
- Now go back to the previous page (using the browser's back button)
- You are no longer able to type in the search box
The box contains the partial text and is clickable but it is not editable. On Chrome the text disappears completely after going to previous page. My Firefox version is 57.0.2.

**Comment by zk** [comment]
Fixed by #183

**Comment by orangeblock** [comment]
Looks like it's still an issue for me. Tried with both http and https versions.

**Comment by zk** [comment]
@orangeblock just got this noti but not seeing your comment on this issue.

![image](https://user-images.githubusercontent.com/7194/37683209-ea4f2484-2c2f-11e8-8949-f0c7b4763b7c.png)

**Comment by orangeblock** [comment]
Yeah, sorry I did write the comment but then I realized you might have not pushed the changes to the live version. If that's not the case, then yes I still have the issue outlined above.

**Comment by zk** [comment]
No worries, yeah I pushed those changes yesterday so this should still be open. Thanks for checking.
