### ISSUE TITLE
503 (Bad Gateway) response from Clojure doc server

### ISSUE THREAD

**Issue by KTAtkinson** [zk/clojuredocs#258]
When I go to https://clojuredocs.org/ I get this page from Cloudflare. ![Screenshot_20241230-105147](https://github.com/user-attachments/assets/c43801b9-5b9e-4ba0-9ca3-64df5c21c431)

**Comment by zk** [comment]
Thanks Katie, will take a look later today

**Comment by MrMil** [comment]
Any news on when it'll come back up?

**Comment by Ajetski** [comment]
As a stop-gap i'm hosting a copy here: [ajet.lol:42411](http://ajet.lol:42411
)
I use a proxy for local convenience and inter-op with Clojure cheat sheet for now.

I'll take this down once 502 is resolved

**Comment by zk** [comment]
Fixed

**Comment by vpalichev** [comment]
I still have issues with clojuredocs.org -- loading is slow, at first it seems like the site is not accessible, browser shows blank white page in process of loading for 30-50-100 seconds (and more!), then it opens. 
After December 30th the site haven't yet worked smoothly for me.
Can anyone confirm?
